# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include [override.d, override.yaml]

logging: !include logging.yaml

kvmd:
    server:
        unix: /run/kvmd/kvmd.sock
        unix_mode: 0666

    auth: !include auth.yaml

    hid:
        type: otg
        keyboard:
            device: /dev/null
        mouse:
            device: /dev/null
        noop: true
        
    atx:
        type: disabled

    msd:
        type: disabled

    streamer:
        unix: /run/kvmd/ustreamer.sock
        desired_fps: 30
        max_fps: 40
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--resolution=800x600"
            - "--last-as-blank=0"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0666"
            - "--exit-on-parent-death"
            - "--process-name-prefix={process_name_prefix}"
            - "--notify-parent"
            - "--no-log-colors"
    gpio:
        drivers:
            __gpio__: 
                type: cmd
                cmd: [/bin/ls, -l]

ipmi:
    kvmd:
        unix: /run/kvmd/kvmd.sock

vnc:
    kvmd:
        unix: /run/kvmd/kvmd.sock

    streamer:
        unix: /run/kvmd/ustreamer.sock

    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"

    server:
        tls:
            x509:
                cert: /etc/kvmd/vnc/ssl/server.crt
                key: /etc/kvmd/vnc/ssl/server.key
janus:
    cmd:
        - "/bin/true"

otgnet:
    commands:
        post_start_cmd:
            - "/bin/true"
        pre_stop_cmd:
            - "/bin/true"